// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Non-pooled connection, used only by the Prisma CLI (migrate, etc).
    // The app itself connects via the adapter with DATABASE_URL (pooled) —
    // see src/lib/prisma.ts / prisma/seed.ts. Neon's "-pooler" endpoint
    // (DATABASE_URL) doesn't support the advisory locks Migrate needs,
    // which caused repeated P1002 timeouts on deploy.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
